### PR TITLE
Xushnud

### PR DESCRIPTION
**Pull request by Hushnudbek04**

### CODE REVIEW

**Comment by Hushnudbek04** [comment]
My deadline ends on January 31, please check it soon

**Comment by bahtibek-an** [comment]
Send me full name since i can't identificate you

**Comment by Hushnudbek04** [comment]
Qurbonboyev Xushnud

**Comment by Hushnudbek04** [comment]
my name is Qurbonboyev Hushnud

**Comment by Hushnudbek04** [comment]
My name in Qwasar  is qurbonbo_h

**Review by bahtibek-an — CHANGES_REQUESTED** [review]
If i try to upload the post, then i got this error in devtools
```
{
  "error": {
    "code": 403,
    "message": "Permission denied."
  }
}
```
And after reloading this page shows 404 Not Found
image

**Pull request closed without merging**
